version: '3'
services:
  node:
    build:
      context: .
      dockerfile: test.Dockerfile
    command: npm run test
    ports:
      - 80:3000
    env_file:
      - ./.env
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:

